#!/bin/bash
cd .. && find "$(basename "$PWD")" -maxdepth 1 -type f -name "*.html" -exec sh -c 'for file; do [ ! -e "$(dirname "$0")/$file" ] || [ "$file" -nt "$(dirname "$0")/$file" ] && cp -p "$file" "$(dirname "$0")"; done' "$PWD" {} +
